ERROR - 2022-12-06 06:53:09 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp7\\htdoc...', 171)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://sfourt....', 'id19969705_admi...', 'Sasat09_+_+_+', 'id19969705_json...', 3306, '', 0)
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#7 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#9 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://sfourt....', 'id19969705_admi...', 'Sasat09_+_+_+', 'id19969705_json...', 3306, '', 0)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#7 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#6 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#7 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#11 {main}
CRITICAL - 2022-12-06 06:53:09 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for https failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Login->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-06 06:53:20 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp7\\htdoc...', 171)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://sfourt....', 'id19969705_admi...', 'Sasat09_+_+_+', 'id19969705_json...', 3306, '', 0)
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#7 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#9 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://sfourt....', 'id19969705_admi...', 'Sasat09_+_+_+', 'id19969705_json...', 3306, '', 0)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#7 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#6 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#7 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#11 {main}
CRITICAL - 2022-12-06 06:53:20 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for https failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Login->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-06 06:55:08 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp7\\htdoc...', 171)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://sfourt....', 'id19969705_admi...', 'Sasat09_+_+_+', 'id19969705_json...', 3306, '', 0)
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#7 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#9 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('https://sfourt....', 'id19969705_admi...', 'Sasat09_+_+_+', 'id19969705_json...', 3306, '', 0)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#7 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for https failed: No such host is known.  in C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 C:\xampp7\htdocs\APIclubhouse\app\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
#6 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\Login->index()
#7 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp7\htdocs\APIclubhouse\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp7\htdocs\APIclubhouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp7\\htdoc...')
#11 {main}
CRITICAL - 2022-12-06 06:55:08 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for https failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(32): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Login->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
